### ISSUE TITLE
[enhancement] Add main file.

### ISSUE THREAD

**Issue by shachar1lavi** [ofer1katz/ivbscript#1]
@ofer1katz Can you give permissions to add a new branch in order to start a pull request?

Something like this:
####  ivbscript\main.py
```python
from jupyter_console.app import ZMQTerminalIPythonApp


def main():
    """ Launch iVBScript Shell """
    ZMQTerminalIPythonApp.launch_instance(argv=['--kernel', 'vbscript'])


if __name__ == '__main__':
    main()

```

**Comment by ofer1katz** [comment]
הוספתי הרשאות אבל אני די בטוח שניסיתי את מה ששלחת וזה לא עבד

**Comment by ofer1katz** [comment]
added a new entry point with to following code.
Thank you 👍

**Comment by ofer1katz** [comment]
You got an invitation to become a collaborator.
